FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install && rm -rf /usr/local/lib/node_modules/npm

COPY . .

EXPOSE 3000

CMD ["node", "node_modules/react-scripts/bin/react-scripts.js", "start"]
